spring.application.name=weather.metrics
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
#langchain4j.open-ai.chat-model.base-url=https://api.openai.com/


logging.level.dev.langchain4j=DEBUG
logging.level.dev.langchain4j.internal.RetryUtils=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http.client=DEBUG
